import { User, PlatformAccount, Conversation, SystemStatus, ActivityItem, AIAgent } from '@/types';

export const mockUser: User = {
  id: 'user-1',
  name: 'Alex Morgan',
  email: 'alex@nexusai.com',
  role: 'admin',
  avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&q=80',
};

export const mockAccounts: PlatformAccount[] = [
  {
    id: 'acc-1',
    platform: 'upwork',
    accountName: 'ProDev Solutions',
    username: 'prodev_alex',
    isActive: true,
    autoBidEnabled: true,
    dailyBudget: 500,
    bidCount: 23,
    successRate: 34,
    aiPrompt: 'Focus on web development projects with React and Node.js. Budget range: $1000-$5000.',
    lastActivity: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: 'acc-2',
    platform: 'upwork',
    accountName: 'AI Automation Expert',
    username: 'ai_expert_pro',
    isActive: true,
    autoBidEnabled: false,
    dailyBudget: 300,
    bidCount: 18,
    successRate: 41,
    aiPrompt: 'Target AI/ML automation projects. Minimum budget: $2000.',
    lastActivity: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: 'acc-3',
    platform: 'fiverr',
    accountName: 'WebFlow Master',
    username: 'webflow_master',
    isActive: true,
    autoBidEnabled: true,
    dailyBudget: 200,
    bidCount: 31,
    successRate: 52,
    aiPrompt: 'Focus on Webflow and no-code solutions.',
    lastActivity: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
  {
    id: 'acc-4',
    platform: 'fiverr',
    accountName: 'Full Stack Dev',
    username: 'fullstack_dev',
    isActive: false,
    autoBidEnabled: false,
    dailyBudget: 400,
    bidCount: 12,
    successRate: 28,
    lastActivity: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
];

export const mockConversations: Conversation[] = [
  {
    id: 'conv-1',
    clientName: 'Sarah Johnson',
    clientAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80',
    platform: 'upwork',
    lastMessage: 'Thanks! When can you start?',
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    unreadCount: 2,
    projectTitle: 'E-commerce Platform Development',
    messages: [
      {
        id: 'msg-1',
        conversationId: 'conv-1',
        sender: 'client',
        content: 'Hi, I saw your proposal for the e-commerce project.',
        timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
        platform: 'upwork',
        read: true,
      },
      {
        id: 'msg-2',
        conversationId: 'conv-1',
        sender: 'user',
        content: 'Hello Sarah! Yes, I\'d be happy to discuss the project details with you.',
        timestamp: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
        platform: 'upwork',
        read: true,
      },
      {
        id: 'msg-3',
        conversationId: 'conv-1',
        sender: 'client',
        content: 'Great! Can you handle both frontend and backend?',
        timestamp: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
        platform: 'upwork',
        read: true,
      },
      {
        id: 'msg-4',
        conversationId: 'conv-1',
        sender: 'user',
        content: 'Absolutely! I specialize in full-stack development with React and Node.js.',
        timestamp: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
        platform: 'upwork',
        read: true,
      },
      {
        id: 'msg-5',
        conversationId: 'conv-1',
        sender: 'client',
        content: 'Thanks! When can you start?',
        timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
        platform: 'upwork',
        read: false,
      },
    ],
  },
  {
    id: 'conv-2',
    clientName: 'Michael Chen',
    clientAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80',
    platform: 'fiverr',
    lastMessage: 'Could you send me some portfolio examples?',
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    unreadCount: 1,
    projectTitle: 'AI Chatbot Integration',
    messages: [
      {
        id: 'msg-6',
        conversationId: 'conv-2',
        sender: 'client',
        content: 'Hi! I need help integrating an AI chatbot into my website.',
        timestamp: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
        platform: 'fiverr',
        read: true,
      },
      {
        id: 'msg-7',
        conversationId: 'conv-2',
        sender: 'client',
        content: 'Could you send me some portfolio examples?',
        timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
        platform: 'fiverr',
        read: false,
      },
    ],
  },
  {
    id: 'conv-3',
    clientName: 'Emma Williams',
    clientAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&q=80',
    platform: 'upwork',
    lastMessage: 'Perfect! Let\'s move forward with the contract.',
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    unreadCount: 0,
    projectTitle: 'Mobile App Development',
    messages: [
      {
        id: 'msg-8',
        conversationId: 'conv-3',
        sender: 'client',
        content: 'I need a React Native app for iOS and Android.',
        timestamp: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
        platform: 'upwork',
        read: true,
      },
      {
        id: 'msg-9',
        conversationId: 'conv-3',
        sender: 'user',
        content: 'I can definitely help with that. What\'s your timeline?',
        timestamp: new Date(Date.now() - 1000 * 60 * 80).toISOString(),
        platform: 'upwork',
        read: true,
      },
      {
        id: 'msg-10',
        conversationId: 'conv-3',
        sender: 'client',
        content: 'Perfect! Let\'s move forward with the contract.',
        timestamp: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
        platform: 'upwork',
        read: true,
      },
    ],
  },
  {
    id: 'conv-4',
    clientName: 'David Martinez',
    platform: 'whatsapp',
    lastMessage: 'Can we schedule a call tomorrow?',
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    unreadCount: 0,
    messages: [
      {
        id: 'msg-11',
        conversationId: 'conv-4',
        sender: 'client',
        content: 'Hey, got your number from the Fiverr project.',
        timestamp: new Date(Date.now() - 1000 * 60 * 150).toISOString(),
        platform: 'whatsapp',
        read: true,
      },
      {
        id: 'msg-12',
        conversationId: 'conv-4',
        sender: 'client',
        content: 'Can we schedule a call tomorrow?',
        timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
        platform: 'whatsapp',
        read: true,
      },
    ],
  },
];

export const mockSystemStatus: SystemStatus = {
  apiStatus: 'operational',
  upworkConnected: true,
  fiverrConnected: true,
  whatsappConnected: true,
  activeBids: 47,
  activeConversations: 12,
  lastSync: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
};

export const mockActivities: ActivityItem[] = [
  {
    id: 'act-1',
    type: 'bid_placed',
    title: 'Bid placed',
    description: 'Auto-bid placed on "React Dashboard Development" - $2,500',
    timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    platform: 'upwork',
  },
  {
    id: 'act-2',
    type: 'message_received',
    title: 'New message',
    description: 'Sarah Johnson: Thanks! When can you start?',
    timestamp: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    platform: 'upwork',
  },
  {
    id: 'act-3',
    type: 'bid_won',
    title: 'Bid won!',
    description: 'Your bid on "AI Integration Project" was accepted',
    timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    platform: 'fiverr',
  },
  {
    id: 'act-4',
    type: 'account_connected',
    title: 'Account connected',
    description: 'WebFlow Master account successfully connected',
    timestamp: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    platform: 'fiverr',
  },
];

export const mockAIAgents: AIAgent[] = [
  {
    id: 'agent-1',
    name: 'Client Closing Agent',
    description: 'AI-powered assistant to help close deals and convert leads',
    icon: 'target',
    category: 'sales',
  },
  {
    id: 'agent-2',
    name: 'Scope Analyzer',
    description: 'Analyze project requirements and generate detailed scopes',
    icon: 'file-search',
    category: 'analysis',
  },
  {
    id: 'agent-3',
    name: 'Proposal Generator',
    description: 'Create compelling proposals tailored to client needs',
    icon: 'file-text',
    category: 'content',
  },
  {
    id: 'agent-4',
    name: 'Message Composer',
    description: 'Generate professional client messages and responses',
    icon: 'message-square',
    category: 'content',
  },
  {
    id: 'agent-5',
    name: 'Ad Creator',
    description: 'Design and generate marketing ads for your services',
    icon: 'megaphone',
    category: 'content',
  },
  {
    id: 'agent-6',
    name: 'Price Calculator',
    description: 'Calculate optimal pricing based on project scope',
    icon: 'calculator',
    category: 'analysis',
  },
];
